# SwiftLint Configuration for F1Manager

# 포함할 디렉토리
included:
  - Projects
  - Tuist

# 제외할 디렉토리
excluded:
  - Pods
  - DerivedData
  - .build
  - Projects/**/Generated

# 활성화할 규칙
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 비활성화할 규칙
disabled_rules:
  - trailing_whitespace # 자동 포맷팅으로 처리

# F1Manager 특화 커스텀 규칙
custom_rules:
  # forEach addSubview 금지
  no_foreach_addsubview:
    name: "No forEach addSubview"
    regex: '\.forEach\s*{\s*.*\.addSubview'
    message: "Use individual addSubview calls instead of forEach"
    severity: error

  # 하드코딩된 한글 문자열 금지
  no_hardcoded_korean:
    name: "No hardcoded Korean strings"
    regex: '"[가-힣]+'
    message: "Use NSLocalizedString instead of hardcoded Korean strings"
    severity: warning

  # Clean Architecture 레이어 위반 체크
  data_layer_isolation:
    name: "Data layer should not import Presentation"
    regex: 'import\s+.*Presentation'
    match_kinds:
      - identifier
    message: "Data layer should not import Presentation layer"
    severity: error

  # Coordinator weak 참조 체크
  coordinator_weak_reference:
    name: "Coordinator properties should be weak"
    regex: '(var|let)\s+(finishDelegate|navigationController):\s*[^?]*\??\s*$'
    message: "Coordinator delegates and navigation controllers should be weak"
    severity: warning

# 규칙별 설정
file_length:
  warning: 400
  error: 500

line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 80

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - uri
    - api
    - db

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# 파일 헤더 설정
file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  .*
    \/\/
    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2}\.
    \/\/  Copyright © \d{4} com\.junhyeok\.F1Manager\. All rights reserved\.
    \/\/

# 리포터 설정
reporter: "xcode"

# 병렬 처리 활성화
strict: true